api_key_path: "C:/Users/user/Documents/projects/api_key.txt"
#model_name: "gemini-2.5-pro"
model_name: "gemini-2.5-flash"
target_dir: "C:/Users/user/Documents/projects/SomeDocuments/Note/experiment"

steps:
  recorder:
    input: "memo.md"
    output: "note.md"
  researcher:
    input:
      - "note.md"
      - "research.md"
    output: "setting.md"
  planner:
    input: "setting.md"
    output: "plan.md"
  plotter:
    input: "plan.md"
    output: "plot.md"
  writer:
    input: "plot.md"
    output: "novel.md"
  illustrator:
    input: "novel.md"
    output: "illust.png"